// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/jimtrung/go-nexus/templates/layout"

func ResetPassword() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex min-h-screen items-center justify-center\n                    bg-gray-100\"><div class=\"w-full max-w-md space-y-6 rounded-lg bg-white\n                        p-8 shadow-md\"><h2 class=\"text-center text-2xl font-bold text-gray-900\">Reset Password</h2><p class=\"text-center text-gray-600\">Enter your new password below.</p><form hx-post=\"/auth/reset-password\" hx-target=\"#reset-feedback\" hx-vals=\"js:{ token: window.location.pathname\n                                       .split(&#34;/&#34;).pop() }\" hx-swap=\"innerHTML\" hx-ext=\"json-enc\" class=\"space-y-4\"><div><label class=\"block text-sm font-medium\n                                      text-gray-700\">New Password</label> <input type=\"password\" name=\"password\" required class=\"mt-1 w-full rounded-lg border p-2\n                                      focus:border-blue-500\n                                      focus:ring-blue-500\"></div><div><label class=\"block text-sm font-medium\n                                      text-gray-700\">Confirm New Password</label> <input type=\"password\" name=\"confirm_password\" required class=\"mt-1 w-full rounded-lg\n                                          border p-2 focus:border-blue-500\n                                          focus:ring-blue-500\"></div><button type=\"submit\" class=\"w-full rounded-lg bg-blue-500 px-4\n                                   py-2 text-white hover:bg-blue-600\">Reset Password</button></form><div id=\"reset-feedback\" class=\"text-center text-red-500\"></div><p class=\"text-center text-gray-600\">Remembered your password? <a href=\"/p/user/login\" class=\"text-blue-500 hover:underline\">Go back to login</a></p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Reset Password").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
